build(deps-dev): Bump esbuild from 0.11.8 to 0.11.10 (#263)
Bumps [esbuild](https://github.com/evanw/esbuild) from 0.11.8 to 0.11.10.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/evanw/esbuild/releases">esbuild's releases</a>.</em></p>
<blockquote>
<h2>v0.11.10</h2>
<ul>
<li>
<p>Provide more information about <code>exports</code> map import failures if possible (<a href="https://github-redirect.dependabot.com/evanw/esbuild/issues/1143">#1143</a>)</p>
<p>Node has a new feature where you can <a href="https://nodejs.org/api/packages.html#packages_package_entry_points">add an <code>exports</code> map to your <code>package.json</code> file</a> to control how external import paths map to the files in your package. You can change which paths map to which files as well as make it impossible to import certain files (i.e. the files are private).</p>
<p>If path resolution fails due to an <code>exports</code> map and the failure is not related to import conditions, esbuild's current error message for this just says that the import isn't possible:</p>
<pre><code> &gt; example.js:1:15: error: Could not resolve &quot;vanillajs-datepicker/js/i18n/locales/ca&quot; (mark it as external to exclude it from the bundle)
    1 │ import ca from 'vanillajs-datepicker/js/i18n/locales/ca'
      ╵                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   node_modules/vanillajs-datepicker/package.json:6:13: note: The path &quot;./js/i18n/locales/ca&quot; is not exported by package &quot;vanillajs-datepicker&quot;
    6 │   &quot;exports&quot;: {
      ╵              ^
</code></pre>
<p>This error message matches the error that node itself throws. However, the message could be improved in the case where someone is trying to import a file using its file system path and that path is actually exported by the package, just under a different export path. This case comes up a lot when using TypeScript because the TypeScript compiler (and therefore the Visual Studio Code IDE) <a href="https://github-redirect.dependabot.com/microsoft/TypeScript/issues/33079">still doesn't support package <code>exports</code></a>.</p>
<p>With this release, esbuild will now do a reverse lookup of the file system path using the <code>exports</code> map to determine what the correct import path should be:</p>
<pre><code> &gt; example.js:1:15: error: Could not resolve &quot;vanillajs-datepicker/js/i18n/locales/ca&quot; (mark it as external to exclude it from the bundle)
     1 │ import ca from 'vanillajs-datepicker/js/i18n/locales/ca'
       ╵                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   node_modules/vanillajs-datepicker/package.json:6:13: note: The path &quot;./js/i18n/locales/ca&quot; is not exported by package &quot;vanillajs-datepicker&quot;
     6 │   &quot;exports&quot;: {
       ╵              ^
   node_modules/vanillajs-datepicker/package.json:12:19: note: The file &quot;./js/i18n/locales/ca.js&quot; is exported at path &quot;./locales/ca&quot;
    12 │     &quot;./locales/*&quot;: &quot;./js/i18n/locales/*.js&quot;,
       ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~
   example.js:1:15: note: Import from &quot;vanillajs-datepicker/locales/ca&quot; to get the file &quot;node_modules/vanillajs-datepicker/js/i18n/locales/ca.js&quot;
     1 │ import ca from 'vanillajs-datepicker/js/i18n/locales/ca'
       │                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       ╵                &quot;vanillajs-datepicker/locales/ca&quot;
</code></pre>
<p>Hopefully this should enable people encountering this issue to fix the problem themselves.</p>
</li>
</ul>
<h2>v0.11.9</h2>
<ul>
<li>
<p>Fix escaping of non-BMP characters in property names (<a href="https://github-redirect.dependabot.com/evanw/esbuild/issues/977">#977</a>)</p>
<p>Property names in object literals do not have to be quoted if the property is a valid JavaScript identifier. This is defined as starting with a character in the <code>ID_Start</code> Unicode category and ending with zero or more characters in the <code>ID_Continue</code> Unicode category. However, esbuild had a bug where non-BMP characters (i.e. characters encoded using two UTF-16 code units instead of one) were always checked against <code>ID_Continue</code> instead of <code>ID_Start</code> because they included a code unit that wasn't at the start. This could result in invalid JavaScript being generated when using <code>--charset=utf8</code> because <code>ID_Continue</code> is a superset of <code>ID_Start</code> and contains some characters that are not valid at the start of an identifier. This bug has been fixed.</p>
</li>
<li>
<p>Be maximally liberal in the interpretation of the <code>browser</code> field (<a href="https://github-redirect.dependabot.com/evanw/esbuild/issues/740">#740</a>)</p>
<p>The <code>browser</code> field in <code>package.json</code> is an informal convention followed by browser-specific bundlers that allows package authors to substitute certain node-specific import paths with alternative browser-specific import paths. It doesn't have a rigorous specification and the <a href="https://github.com/defunctzombie/package-browser-field-spec">canonical description</a> of the feature doesn't include any tests. As a result, each bundler implements this feature differently. I have tried to create a <a href="https://github.com/evanw/package-json-browser-tests">survey of how different bundlers interpret the <code>browser</code> field</a> and the results are very inconsistent.</p>
<p>This release attempts to change esbuild to support the union of the behavior of all other bundlers. That way if people have the <code>browser</code> field working with some other bundler and they switch to esbuild, the <code>browser</code> field shouldn't ever suddenly stop working. This seemed like the most principled approach to take in this situation.</p>
<p>The drawback of this approach is that it means the <code>browser</code> field may start working when switching to esbuild when it was previously not working. This could cause bugs, but I consider this to be a problem with the package (i.e. not using a more well-supported form of the <code>browser</code> field), not a problem with esbuild itself.</p>
</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/evanw/esbuild/blob/master/CHANGELOG.md">esbuild's changelog</a>.</em></p>
<blockquote>
<h2>0.11.10</h2>
<ul>
<li>
<p>Provide more information about <code>exports</code> map import failures if possible (<a href="https://github-redirect.dependabot.com/evanw/esbuild/issues/1143">#1143</a>)</p>
<p>Node has a new feature where you can <a href="https://nodejs.org/api/packages.html#packages_package_entry_points">add an <code>exports</code> map to your <code>package.json</code> file</a> to control how external import paths map to the files in your package. You can change which paths map to which files as well as make it impossible to import certain files (i.e. the files are private).</p>
<p>If path resolution fails due to an <code>exports</code> map and the failure is not related to import conditions, esbuild's current error message for this just says that the import isn't possible:</p>
<pre><code> &gt; example.js:1:15: error: Could not resolve &quot;vanillajs-datepicker/js/i18n/locales/ca&quot; (mark it as external to exclude it from the bundle)
    1 │ import ca from 'vanillajs-datepicker/js/i18n/locales/ca'
      ╵                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   node_modules/vanillajs-datepicker/package.json:6:13: note: The path &quot;./js/i18n/locales/ca&quot; is not exported by package &quot;vanillajs-datepicker&quot;
    6 │   &quot;exports&quot;: {
      ╵              ^
</code></pre>
<p>This error message matches the error that node itself throws. However, the message could be improved in the case where someone is trying to import a file using its file system path and that path is actually exported by the package, just under a different export path. This case comes up a lot when using TypeScript because the TypeScript compiler (and therefore the Visual Studio Code IDE) <a href="https://github-redirect.dependabot.com/microsoft/TypeScript/issues/33079">still doesn't support package <code>exports</code></a>.</p>
<p>With this release, esbuild will now do a reverse lookup of the file system path using the <code>exports</code> map to determine what the correct import path should be:</p>
<pre><code> &gt; example.js:1:15: error: Could not resolve &quot;vanillajs-datepicker/js/i18n/locales/ca&quot; (mark it as external to exclude it from the bundle)
     1 │ import ca from 'vanillajs-datepicker/js/i18n/locales/ca'
       ╵                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   node_modules/vanillajs-datepicker/package.json:6:13: note: The path &quot;./js/i18n/locales/ca&quot; is not exported by package &quot;vanillajs-datepicker&quot;
     6 │   &quot;exports&quot;: {
       ╵              ^
   node_modules/vanillajs-datepicker/package.json:12:19: note: The file &quot;./js/i18n/locales/ca.js&quot; is exported at path &quot;./locales/ca&quot;
    12 │     &quot;./locales/*&quot;: &quot;./js/i18n/locales/*.js&quot;,
       ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~
   example.js:1:15: note: Import from &quot;vanillajs-datepicker/locales/ca&quot; to get the file &quot;node_modules/vanillajs-datepicker/js/i18n/locales/ca.js&quot;
     1 │ import ca from 'vanillajs-datepicker/js/i18n/locales/ca'
       │                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       ╵                &quot;vanillajs-datepicker/locales/ca&quot;
</code></pre>
<p>Hopefully this should enable people encountering this issue to fix the problem themselves.</p>
</li>
</ul>
<h2>0.11.9</h2>
<ul>
<li>
<p>Fix escaping of non-BMP characters in property names (<a href="https://github-redirect.dependabot.com/evanw/esbuild/issues/977">#977</a>)</p>
<p>Property names in object literals do not have to be quoted if the property is a valid JavaScript identifier. This is defined as starting with a character in the <code>ID_Start</code> Unicode category and ending with zero or more characters in the <code>ID_Continue</code> Unicode category. However, esbuild had a bug where non-BMP characters (i.e. characters encoded using two UTF-16 code units instead of one) were always checked against <code>ID_Continue</code> instead of <code>ID_Start</code> because they included a code unit that wasn't at the start. This could result in invalid JavaScript being generated when using <code>--charset=utf8</code> because <code>ID_Continue</code> is a superset of <code>ID_Start</code> and contains some characters that are not valid at the start of an identifier. This bug has been fixed.</p>
</li>
<li>
<p>Be maximally liberal in the interpretation of the <code>browser</code> field (<a href="https://github-redirect.dependabot.com/evanw/esbuild/issues/740">#740</a>)</p>
<p>The <code>browser</code> field in <code>package.json</code> is an informal convention followed by browser-specific bundlers that allows package authors to substitute certain node-specific import paths with alternative browser-specific import paths. It doesn't have a rigorous specification and the <a href="https://github.com/defunctzombie/package-browser-field-spec">canonical description</a> of the feature doesn't include any tests. As a result, each bundler implements this feature differently. I have tried to create a <a href="https://github.com/evanw/package-json-browser-tests">survey of how different bundlers interpret the <code>browser</code> field</a> and the results are very inconsistent.</p>
<p>This release attempts to change esbuild to support the union of the behavior of all other bundlers. That way if people have the <code>browser</code> field working with some other bundler and they switch to esbuild, the <code>browser</code> field shouldn't ever suddenly stop working. This seemed like the most principled approach to take in this situation.</p>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/evanw/esbuild/commit/a2d1b2a531491ca1f2901b89d99680e85f228cc7"><code>a2d1b2a</code></a> publish 0.11.10 to npm</li>
<li><a href="https://github.com/evanw/esbuild/commit/a14db0d9cf9b0dfc657fe7fba68af3763829dea5"><code>a14db0d</code></a> fix typescript type checking tests</li>
<li><a href="https://github.com/evanw/esbuild/commit/d4a7cd31db5b8652755b7539e6b164ff806fce70"><code>d4a7cd3</code></a> Experimental support for Deno (<a href="https://github-redirect.dependabot.com/evanw/esbuild/issues/1145">#1145</a>)</li>
<li><a href="https://github.com/evanw/esbuild/commit/c5a88a04561debf302243b0afd11d365257a2373"><code>c5a88a0</code></a> add better error message for <a href="https://github-redirect.dependabot.com/evanw/esbuild/issues/1143">#1143</a></li>
<li><a href="https://github.com/evanw/esbuild/commit/2e61c46b68dcc541c1bb098c0f4d85d3f75f1c94"><code>2e61c46</code></a> batch tests to hopefully fix ci memory issues</li>
<li><a href="https://github.com/evanw/esbuild/commit/01cad40507c3e6d0ffcb408cc92c08ae8792e92a"><code>01cad40</code></a> better indenting for debug logs</li>
<li><a href="https://github.com/evanw/esbuild/commit/3a837f825155720f1265afd674e81f92893fd75f"><code>3a837f8</code></a> add more debug logs for ESM package resolution</li>
<li><a href="https://github.com/evanw/esbuild/commit/d616dac2ca7cb0f9bd918b96fa44ece3578ee9b3"><code>d616dac</code></a> publish 0.11.9 to npm</li>
<li><a href="https://github.com/evanw/esbuild/commit/a1983043a963c28a02799d7232bd4e752a13bd85"><code>a198304</code></a> Be maximally liberal in the interpretation of the <code>browser</code> field (<a href="https://github-redirect.dependabot.com/evanw/esbuild/issues/1140">#1140</a>)</li>
<li><a href="https://github.com/evanw/esbuild/commit/eac9513c8588a80de45de84aa8a3d9fbe01d2679"><code>eac9513</code></a> fix non-bmp characters in identifier validation (<a href="https://github-redirect.dependabot.com/evanw/esbuild/issues/1139">#1139</a>)</li>
<li>Additional commits viewable in <a href="https://github.com/evanw/esbuild/compare/v0.11.8...v0.11.10">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=esbuild&package-manager=npm_and_yarn&previous-version=0.11.8&new-version=0.11.10)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually


</details>